# Generated by Django 3.1.7 on 2021-05-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.IntegerField()),
                ('set_to_expire', models.CharField(default='n', max_length=1)),
                ('file_name', models.CharField(default='UN-NAMED', max_length=100)),
                ('audio_file', models.CharField(default='sadface.mp3', max_length=100)),
            ],
        ),
    ]
